### ISSUE TITLE
Publish v0.22.0 to CocoaPods

### ISSUE THREAD

**Issue by vyshane** [vyshane/grpc-swift-combine#17]
The release of [CombineGRPC 0.22.0](https://github.com/vyshane/grpc-swift-combine/releases/tag/0.22.0) to CocoaPods is currently blocked by the release of upstream dependency of [Swift gRPC 1.0.0-alpha.21](https://github.com/grpc/grpc-swift/releases/tag/1.0.0-alpha.21) to CocoaPods.

Release of Swift gRPC to CocoaPods is in turn blocked by Swift NIO. See: grpc/grpc-swift#1056.

**Comment by moh-abk** [comment]
It’s been resolved 😻

**Comment by vyshane** [comment]
Thanks, I will push a release to CocoaPods.

**Comment by vyshane** [comment]
I've pushed 0.22.0 to CocoaPods.

**Comment by moh-abk** [comment]
I can confirm the below combinations work perfect;

```
pod 'gRPC-Swift', '1.0.0-alpha.21'
pod 'CombineGRPC', '~> 0.22'
```

**Comment by vyshane** [comment]
Thanks for checking - closing.
