### ISSUE TITLE
bitcode error - 0.21.0

### ISSUE THREAD

**Issue by moh-abk** [vyshane/grpc-swift-combine#18]
Finally got around upgrading using Pods from 0.17 to 0.21 and getting this error when trying to build;

![CleanShot 2020-12-03 at 22 52 40@2x](https://user-images.githubusercontent.com/7813457/101105420-70122980-35c5-11eb-857c-a84c5f32c22e.png)

**Comment by vyshane** [comment]
I've had issues getting the pod to work with XCTest dependency. To get around this I have removed [CompletionExpectations](https://github.com/vyshane/grpc-swift-combine/blob/master/Tests/CombineGRPCTests/CompletionExpectations.swift) from the CombineGRPC public API in [0.22.0](https://github.com/vyshane/grpc-swift-combine/releases/tag/0.22.0). Can you try that release?

**Comment by moh-abk** [comment]
Awesome - I can confirm the below combinations work perfect;

```
pod 'gRPC-Swift', '1.0.0-alpha.21'
pod 'CombineGRPC', '~> 0.22'
```

I'm trying to get off `Pods` but adding both `grpc-swift` and `CombineGRPC` using `SPM` produces an error related to your tests also - I'll remove the pods and try SPM and raise another issue with the error logs.
