### ISSUE TITLE
discussion - GRPCError should implement error

### ISSUE THREAD

**Issue by moh-abk** [vyshane/grpc-swift-combine#19]
Based on the great work done in https://github.com/vyshane/grpc-swift-combine/issues/12 - I think `GRPCError` should implement `Error` rather than `GRPCStatus` implementing it.

Currently you have to do example `Future<SomeResponse, GRPCStatus>` -- but with `GRPCError` containing other stuff that might be needed downstream I think it should implement `Error`.

Most Combine publishers require an `Error` as part of the return.

Thoughts?

**Comment by vyshane** [comment]
I don't have control over the `GRPCError` type. It belongs to upstream Swift gRPC.

`RPCError` [does implement](https://github.com/vyshane/grpc-swift-combine/blob/master/Sources/CombineGRPC/RPCError.swift#L12) `Error` though. Did you confuse the two?

**Comment by moh-abk** [comment]
Indeed I confused them. Thanks!
