### ISSUE TITLE
Support gRPC Swift 1.0.0-alpha.23

### ISSUE THREAD

**Issue by moh-abk** [vyshane/grpc-swift-combine#20]
New grpc-swift version released - https://github.com/grpc/grpc-swift/releases/tag/1.0.0-alpha.23

**Comment by vyshane** [comment]
I have just released [0.24.0](https://github.com/vyshane/grpc-swift-combine/releases/tag/0.24.0). Can you verify that the CocoaPod works for you?

**Comment by moh-abk** [comment]
Awesome - tested all OK! Thanks for the quick action!
