### ISSUE TITLE
Support SwiftGRPC 1.0.0.alpha-10+

### ISSUE THREAD

**Issue by orj** [vyshane/grpc-swift-combine#4]
I was trying to use SwiftGRPC and CombineGRPC on the weekend and noticed some source incompatibilities between your project and version 1.0.0.alpha-10 and above of SwiftGRPC.

Any plan to update in the near future?

**Comment by vyshane** [comment]
Yes, definitely. Am working on an updating to 1.0.0.alpha-11 now.

**Comment by vyshane** [comment]
@cyborgthefirst can you publish tag `cyborgthefirst/grpc-swift:1.0.0-alpha.11` for the Docker image that you maintain at https://hub.docker.com/r/cyborgthefirst/grpc-swift?

**Comment by vyshane** [comment]
I have published a [new version 0.10.0](https://github.com/vyshane/grpc-swift-combine/releases/tag/0.10.0) of CombineGRPC which is compatible with gRPC Swift 1.0.0-alpha.11.
