### ISSUE TITLE
Use @Published variable as input streams in bidirectional streams

### ISSUE THREAD

**Issue by krjw** [vyshane/grpc-swift-combine#6]
Hi,
I am struggling to implement bidirectional streams with a @Published variable as input stream. Do you by any chance have an example?

Great library so far!

Greetings krjw

**Comment by krjw** [comment]
Found the solution:

`self.$publishedVariable.setFailureType(to: Error.self).eraseToAnyPublisher()`

**Comment by vyshane** [comment]
@krjw sorry for the delayed response. I didn't receive a notification when you created this issue. I've just realised that I'm not watching my own repository! I've now fixed that. Glad to see that you managed to resolve the issue.
